### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by nanjizal** [PongoEngine/jasper#1]
I believe the modified BSD is here:
https://opensource.org/licenses/BSD-3-Clause

It's ideal if you setup the license when creating the project then adjust copyright as required. Then it's very clear.
<img width="1109" alt="bsd3" src="https://user-images.githubusercontent.com/20134338/34749334-ca608bcc-f598-11e7-87c4-9b2e129c82a1.png">
A user can quickly see and click on the icon on the header and it takes you directly to the License eg:
https://github.com/Nekith/jsoni18n/blob/master/LICENSE

I only mention this because you currently seem to have two licenses which maybe allowed.
https://github.com/PongoEngine/jasper/blob/master/LICENSE
https://github.com/PongoEngine/jasper/blob/master/COPYING.txt

The second one talks about Kiwi but you have not forked and then overwritten Kiwi, so this confusing.

**Comment by PongoEngine** [comment]
updated
