### ISSUE TITLE
Haxe 4 compatability

### ISSUE THREAD

**Issue by lbergman** [PongoEngine/jasper#2]
I cannot compile jasper using Haxe 4.0.0-preview3 due to various issues in JasperMap. 
First error is ```JasperMap.hx:6: lines 6-66 : Field copy needed by haxe.IMap is missing```
However, fixing that leads to ```Constraint.hx:68: characters 13-56 : key : jasper.ds.JasperMap.K -> Bool should be jasper.Variable -> Bool```

**Comment by Dimous** [comment]
@PongoEngine ping

**Comment by PongoEngine** [comment]
Okay, tests work against 4.0.0-preview.5. Sorry @lbergman for the wait and thank you @Dimous for the ping.
