### ISSUE TITLE
inline methods operators

### ISSUE THREAD

**Issue by francescoagati** [PongoEngine/jasper#3]
hi,
i think that methods operators could be inline for better performance. what do you think?

**Comment by PongoEngine** [comment]
Hello @francescoagati.

I think that inlining most of the methods makes sense. There are a couple cases that may need more investigation but for the most part I'm happy with having any one liner be inline.

Have you experienced any performance issues when using Jasper?

**Comment by francescoagati** [comment]
Not forse now but i think some cases with JavaScript and layout complex with 60 FPS and maybe that inline code can help

**Comment by PongoEngine** [comment]
Method operators are now inline.
