### ISSUE TITLE
compatible for haxe < 4 

### ISSUE THREAD

**Issue by maitag** [PongoEngine/jasper#5]
Ahoi,
for haxe 3 it can not found the KeyValueIterator: <https://github.com/PongoEngine/jasper/blob/master/Sources/jasper/ds/JasperMap.hx#L91>
`#if (haxe_ver >= "4.0.0")` around that function fix it here, but not sure that type is needed somewhere else ;)

Jasper Lib is awesome, great work!

**Comment by PongoEngine** [comment]
Ahoi!

The lib has been updated with the fix. I'm happy to fix any other compatibility issues.
